PROJECT_ROOT="/data1/xuebing/Z25_bam"
PIPELINE_ROOT="/data1/xuebing/Z25_bam/05_IBS_pipeline"

VCF_SOURCE_DIR="${PROJECT_ROOT}/C2_all/VCF"
WORK_ROOT="${PIPELINE_ROOT}/results/C2_2group"
MAP_FILE="${PIPELINE_ROOT}/maps/c2_id_map.txt"

PREFIX="C2_2groups"
GROUP_Y="B25"
GROUP_X="Z23"
GROUP_Y_MATCH_MODE="b25_to_2"
GROUP_X_MATCH_COL="D"
GROUP_X_MATCH_MODE="direct"

BCFTOOLS_BIN="${PROJECT_ROOT}/bcftools"
BGZIP_BIN="${PROJECT_ROOT}/bgzip"
TABIX_BIN="${PROJECT_ROOT}/tabix"
PLINK_BIN="${PROJECT_ROOT}/plink"
PARALLEL_BIN="${PROJECT_ROOT}/parallel"
RSCRIPT_BIN="${PROJECT_ROOT}/Rscript"

THREADS_PARALLEL=8
CHR_SET=42
CHR_LIST="005 006 011 012 017 018 023 024 029 030 035 036 041 042"
PLOIDY_TAG="C2"
GROUP_MODE="2group"

MIN_MAC=2
MAX_GENO=0.3
HIGH_HET_THRESHOLD=0.05
IBS_ZMIN=0.7
IBS_ZMAX=1.0
PLOT_MODE="dna"
MATCH_THRESHOLD=0.99
ALERT_THRESHOLD=0.85
COPY_MODE="link"
